// ignore_for_file: non_constant_identifier_names

final List<Map<String, String>> VERBS = [
    {'present': 'arise', 'past': 'arose', 'perfect': 'arisen', 'spanish': 'surgir, levantarse'},
    {'present': 'awake', 'past': 'awoke', 'perfect': 'awoken', 'spanish': 'despertarse'},
    {'present': 'be', 'past': 'was/were', 'perfect': 'been', 'spanish': 'ser/estar'},
    {'present': 'bear', 'past': 'bore', 'perfect': 'borne/born', 'spanish': 'soportar, dar a luz'},
    {'present': 'beat', 'past': 'beat', 'perfect': 'beaten', 'spanish': 'golpear'},
    {'present': 'become', 'past': 'became', 'perfect': 'become', 'spanish': 'llegar a ser'},
    {'present': 'begin', 'past': 'began', 'perfect': 'begun', 'spanish': 'empezar'},
    {'present': 'bend', 'past': 'bent', 'perfect': 'bent', 'spanish': 'doblar'},
    {'present': 'bet', 'past': 'bet', 'perfect': 'bet', 'spanish': 'apostar'},
    {'present': 'bind', 'past': 'bound', 'perfect': 'bound', 'spanish': 'atar, encuadernar'},
    {'present': 'bid', 'past': 'bid', 'perfect': 'bid', 'spanish': 'pujar'},
    {'present': 'bite', 'past': 'bit', 'perfect': 'bitten', 'spanish': 'morder'},
    {'present': 'bleed', 'past': 'bled', 'perfect': 'bled', 'spanish': 'sangrar'},
    {'present': 'blow', 'past': 'blew', 'perfect': 'blown', 'spanish': 'soplar'},
    {'present': 'break', 'past': 'broke', 'perfect': 'broken', 'spanish': 'romper'},
    {'present': 'breed', 'past': 'bred', 'perfect': 'bred', 'spanish': 'criar'},
    {'present': 'bring', 'past': 'brought', 'perfect': 'brought', 'spanish': 'traer, llevar'},
    {'present': 'broadcast', 'past': 'broadcast', 'perfect': 'broadcast', 'spanish': 'radiar'},
    {'present': 'build', 'past': 'built', 'perfect': 'built', 'spanish': 'edificar'},
    {'present': 'burn', 'past': 'burnt/burned', 'perfect': 'burnt/burned', 'spanish': 'quemar'},
    {'present': 'burst', 'past': 'burst', 'perfect': 'burst', 'spanish': 'reventar'},
    {'present': 'buy', 'past': 'bought', 'perfect': 'bought', 'spanish': 'comprar'},
    {'present': 'cast', 'past': 'cast', 'perfect': 'cast', 'spanish': 'arrojar'},
    {'present': 'catch', 'past': 'caught', 'perfect': 'caught', 'spanish': 'coger'},
    {'present': 'come', 'past': 'came', 'perfect': 'come', 'spanish': 'venir'},
    {'present': 'cost', 'past': 'cost', 'perfect': 'cost', 'spanish': 'costar'},
    {'present': 'cut', 'past': 'cut', 'perfect': 'cut', 'spanish': 'cortar'},
    {'present': 'choose', 'past': 'chose', 'perfect': 'chosen', 'spanish': 'elegir'},
    {'present': 'cling', 'past': 'clung', 'perfect': 'clung', 'spanish': 'agarrarse'},
    {'present': 'creep', 'past': 'crept', 'perfect': 'crept', 'spanish': 'arrastrarse'},
    {'present': 'deal', 'past': 'dealt', 'perfect': 'dealt', 'spanish': 'tratar'},
    {'present': 'dig', 'past': 'dug', 'perfect': 'dug', 'spanish': 'cavar'},
    {'present': 'do', 'past': 'did', 'perfect': 'done', 'spanish': 'hacer'},
    {'present': 'draw', 'past': 'drew', 'perfect': 'drawn', 'spanish': 'dibujar'},
    {'present': 'dream', 'past': 'dreamt/dreamed', 'perfect': 'dreamt/dreamed', 'spanish': 'soñar'},
    {'present': 'drink', 'past': 'drank', 'perfect': 'drunk', 'spanish': 'beber'},
    {'present': 'drive', 'past': 'drove', 'perfect': 'driven', 'spanish': 'conducir'},
    {'present': 'eat', 'past': 'ate', 'perfect': 'eaten', 'spanish': 'comer'},
    {'present': 'fall', 'past': 'fell', 'perfect': 'fallen', 'spanish': 'caer'},
    {'present': 'feed', 'past': 'fed', 'perfect': 'fed', 'spanish': 'alimentar'},
    {'present': 'feel', 'past': 'felt', 'perfect': 'felt', 'spanish': 'sentir'},
    {'present': 'fight', 'past': 'fought', 'perfect': 'fought', 'spanish': 'luchar'},
    {'present': 'find', 'past': 'found', 'perfect': 'found', 'spanish': 'encontrar'},
    {'present': 'flee', 'past': 'fled', 'perfect': 'fled', 'spanish': 'huir'},
    {'present': 'fly', 'past': 'flew', 'perfect': 'flown', 'spanish': 'volar'},
    {'present': 'forbid', 'past': 'forbade', 'perfect': 'forbidden', 'spanish': 'prohibir'},
    {'present': 'forget', 'past': 'forgot', 'perfect': 'forgotten', 'spanish': 'olvidar'},
    {'present': 'forgive', 'past': 'forgave', 'perfect': 'forgiven', 'spanish': 'perdonar'},
    {'present': 'freeze', 'past': 'froze', 'perfect': 'frozen', 'spanish': 'helar'},
    {'present': 'get', 'past': 'got', 'perfect': 'got/gotten', 'spanish': 'obtener'},
    {'present': 'give', 'past': 'gave', 'perfect': 'given', 'spanish': 'dar'},
    {'present': 'go', 'past': 'went', 'perfect': 'gone', 'spanish': 'ir'},
    {'present': 'grow', 'past': 'grew', 'perfect': 'grown', 'spanish': 'crecer'},
    {'present': 'grind', 'past': 'ground', 'perfect': 'ground', 'spanish': 'moler'},
    {'present': 'hang', 'past': 'hung', 'perfect': 'hung', 'spanish': 'colgar'},
    {'present': 'have', 'past': 'had', 'perfect': 'had', 'spanish': 'haber/tener'},
    {'present': 'hear', 'past': 'heard', 'perfect': 'heard', 'spanish': 'oír'},
    {'present': 'hide', 'past': 'hid', 'perfect': 'hidden', 'spanish': 'ocultar'},
    {'present': 'hit', 'past': 'hit', 'perfect': 'hit', 'spanish': 'golpear'},
    {'present': 'hold', 'past': 'held', 'perfect': 'held', 'spanish': 'agarrar'},
    {'present': 'hurt', 'past': 'hurt', 'perfect': 'hurt', 'spanish': 'herir'},
    {'present': 'keep', 'past': 'kept', 'perfect': 'kept', 'spanish': 'conservar'},
    {'present': 'know', 'past': 'knew', 'perfect': 'known', 'spanish': 'saber, conocer'},
    {'present': 'kneel', 'past': 'knelt', 'perfect': 'knelt', 'spanish': 'arrodillarse'},
    {'present': 'knit', 'past': 'knit', 'perfect': 'knit', 'spanish': 'hacer punto'},
    {'present': 'lay', 'past': 'laid', 'perfect': 'laid', 'spanish': 'poner'},
    {'present': 'lead', 'past': 'led', 'perfect': 'led', 'spanish': 'conducir'},
    {'present': 'lean', 'past': 'leant', 'perfect': 'leant', 'spanish': 'apoyarse'},
    {'present': 'leap', 'past': 'leapt', 'perfect': 'leapt', 'spanish': 'brincar'},
    {'present': 'learn', 'past': 'learnt/learned', 'perfect': 'learnt/learned', 'spanish': 'aprender'},
    {'present': 'leave', 'past': 'left', 'perfect': 'left', 'spanish': 'dejar'},
    {'present': 'lend', 'past': 'lent', 'perfect': 'lent', 'spanish': 'prestar'},
    {'present': 'let', 'past': 'let', 'perfect': 'let', 'spanish': 'permitir'},
    {'present': 'lie', 'past': 'lay', 'perfect': 'lain', 'spanish': 'echarse'},
    {'present': 'light', 'past': 'lit', 'perfect': 'lit', 'spanish': 'encender'},
    {'present': 'lose', 'past': 'lost', 'perfect': 'lost', 'spanish': 'perder'},
    {'present': 'make', 'past': 'made', 'perfect': 'made', 'spanish': 'hacer'},
    {'present': 'mean', 'past': 'meant', 'perfect': 'meant', 'spanish': 'significar'},
    {'present': 'meet', 'past': 'met', 'perfect': 'met', 'spanish': 'encontrar'},
    {'present': 'mistake', 'past': 'mistook', 'perfect': 'mistaken', 'spanish': 'equivocar'},
    {'present': 'overcome', 'past': 'overcame', 'perfect': 'overcome', 'spanish': 'vencer'},
    {'present': 'pay', 'past': 'paid', 'perfect': 'paid', 'spanish': 'pagar'},
    {'present': 'put', 'past': 'put', 'perfect': 'put', 'spanish': 'poner'},
    {'present': 'read', 'past': 'read', 'perfect': 'read', 'spanish': 'leer'},
    {'present': 'ride', 'past': 'rode', 'perfect': 'ridden', 'spanish': 'montar'},
    {'present': 'ring', 'past': 'rang', 'perfect': 'rung', 'spanish': 'llamar'},
    {'present': 'rise', 'past': 'rose', 'perfect': 'risen', 'spanish': 'levantarse'},
    {'present': 'run', 'past': 'ran', 'perfect': 'run', 'spanish': 'correr'},
    {'present': 'say', 'past': 'said', 'perfect': 'said', 'spanish': 'decir'},
    {'present': 'see', 'past': 'saw', 'perfect': 'seen', 'spanish': 'ver'},
    {'present': 'seek', 'past': 'sought', 'perfect': 'sought', 'spanish': 'buscar'},
    {'present': 'sell', 'past': 'sold', 'perfect': 'sold', 'spanish': 'vender'},
    {'present': 'send', 'past': 'sent', 'perfect': 'sent', 'spanish': 'enviar'},
    {'present': 'set', 'past': 'set', 'perfect': 'set', 'spanish': 'poner(se)'},
    {'present': 'sew', 'past': 'sewed', 'perfect': 'sewn/sewed', 'spanish': 'coser'},
    {'present': 'shake', 'past': 'shook', 'perfect': 'shaken', 'spanish': 'sacudir'},
    {'present': 'shear', 'past': 'shore', 'perfect': 'shorn', 'spanish': 'esquilar'},
    {'present': 'shine', 'past': 'shone', 'perfect': 'shone', 'spanish': 'brillar'},
    {'present': 'shoot', 'past': 'shot', 'perfect': 'shot', 'spanish': 'disparar'},
    {'present': 'show', 'past': 'showed', 'perfect': 'shown', 'spanish': 'mostrar'},
    {'present': 'shrink', 'past': 'shrank', 'perfect': 'shrunk', 'spanish': 'encogerse'},
    {'present': 'shut', 'past': 'shut', 'perfect': 'shut', 'spanish': 'cerrar'},
    {'present': 'sing', 'past': 'sang', 'perfect': 'sung', 'spanish': 'cantar'},
    {'present': 'sink', 'past': 'sank', 'perfect': 'sunk', 'spanish': 'hundir'},
    {'present': 'sit', 'past': 'sat', 'perfect': 'sat', 'spanish': 'sentarse'},
    {'present': 'sleep', 'past': 'slept', 'perfect': 'slept', 'spanish': 'dormir'},
    {'present': 'slide', 'past': 'slid', 'perfect': 'slid', 'spanish': 'resbalar'},
    {'present': 'smell', 'past': 'smelt', 'perfect': 'smelt', 'spanish': 'oler'},
    {'present': 'sow', 'past': 'sowed', 'perfect': 'sown', 'spanish': 'sembrar'},
    {'present': 'speak', 'past': 'spoke', 'perfect': 'spoken', 'spanish': 'hablar'},
    {'present': 'speed', 'past': 'sped', 'perfect': 'sped', 'spanish': 'acelerar'},
    {'present': 'spell', 'past': 'spelt', 'perfect': 'spelt', 'spanish': 'deletrear'},
    {'present': 'spend', 'past': 'spent', 'perfect': 'spent', 'spanish': 'gastar'},
    {'present': 'spill', 'past': 'spilt/spilled', 'perfect': 'spilt/spilled', 'spanish': 'derramar'},
    {'present': 'spin', 'past': 'spun', 'perfect': 'spun', 'spanish': 'hilar'},
    {'present': 'spit', 'past': 'spat', 'perfect': 'spat', 'spanish': 'escupir'},
    {'present': 'split', 'past': 'split', 'perfect': 'split', 'spanish': 'hender/partir/rajar'},
    {'present': 'spoil', 'past': 'spoilt/spoiled', 'perfect': 'spoilt/spoiled', 'spanish': 'estropear'},
    {'present': 'spread', 'past': 'spread', 'perfect': 'spread', 'spanish': 'extender'},
    {'present': 'spring', 'past': 'sprang', 'perfect': 'sprung', 'spanish': 'saltar'},
    {'present': 'stand', 'past': 'stood', 'perfect': 'stood', 'spanish': 'estar en pie'},
    {'present': 'steal', 'past': 'stole', 'perfect': 'stolen', 'spanish': 'robar'},
    {'present': 'stick', 'past': 'stuck', 'perfect': 'stuck', 'spanish': 'pegar'},
    {'present': 'sting', 'past': 'stung', 'perfect': 'stung', 'spanish': 'picar'},
    {'present': 'stink', 'past': 'stank/stunk', 'perfect': 'stunk', 'spanish': 'apestar'},
    {'present': 'stride', 'past': 'strode', 'perfect': 'stridden', 'spanish': 'dar zancadas'},
    {'present': 'strike', 'past': 'struck', 'perfect': 'struck', 'spanish': 'golpear'},
    {'present': 'swear', 'past': 'swore', 'perfect': 'sworn', 'spanish': 'jurar'},
    {'present': 'sweat', 'past': 'sweat', 'perfect': 'sweat', 'spanish': 'sudar'},
    {'present': 'sweep', 'past': 'swept', 'perfect': 'swept', 'spanish': 'barrer'},
    {'present': 'swell', 'past': 'swelled', 'perfect': 'swollen', 'spanish': 'hinchar'},
    {'present': 'swim', 'past': 'swam', 'perfect': 'swum', 'spanish': 'nadar'},
    {'present': 'swing', 'past': 'swung', 'perfect': 'swung', 'spanish': 'columpiarse'},
    {'present': 'take', 'past': 'took', 'perfect': 'taken', 'spanish': 'coger'},
    {'present': 'teach', 'past': 'taught', 'perfect': 'taught', 'spanish': 'enseñar'},
    {'present': 'tear', 'past': 'tore', 'perfect': 'torn', 'spanish': 'rasgar'},
    {'present': 'tell', 'past': 'told', 'perfect': 'told', 'spanish': 'decir'},
    {'present': 'think', 'past': 'thought', 'perfect': 'thought', 'spanish': 'pensar'},
    {'present': 'throw', 'past': 'threw', 'perfect': 'thrown', 'spanish': 'arrojar'},
    {'present': 'thrust', 'past': 'thrust', 'perfect': 'thrust', 'spanish': 'introducir'},
    {'present': 'tread', 'past': 'trod', 'perfect': 'trodden', 'spanish': 'pisar, hollar'},
    {'present': 'understand', 'past': 'understood', 'perfect': 'understood', 'spanish': 'entender'},
    {'present': 'undergo', 'past': 'underwent', 'perfect': 'undergone', 'spanish': 'sufrir'},
    {'present': 'undertake', 'past': 'undertook', 'perfect': 'undertaken', 'spanish': 'emprender'},
    {'present': 'wake', 'past': 'woke', 'perfect': 'woken', 'spanish': 'despertarse'},
    {'present': 'wear', 'past': 'wore', 'perfect': 'worn', 'spanish': 'llevar puesto'},
    {'present': 'weave', 'past': 'wove', 'perfect': 'woven', 'spanish': 'tejer'},
    {'present': 'weep', 'past': 'wept', 'perfect': 'wept', 'spanish': 'llorar'},
    {'present': 'wet', 'past': 'wet', 'perfect': 'wet', 'spanish': 'mojar'},
    {'present': 'win', 'past': 'won', 'perfect': 'won', 'spanish': 'ganar'},
    {'present': 'wind', 'past': 'wound', 'perfect': 'wound', 'spanish': 'enrollar'},
    {'present': 'withdraw', 'past': 'withdrew', 'perfect': 'withdrawn', 'spanish': 'retirarse'},
    {'present': 'wring', 'past': 'wrung', 'perfect': 'wrung', 'spanish': 'torcer'},
    {'present': 'write', 'past': 'wrote', 'perfect': 'written', 'spanish': 'escribir'},
];
